      DOUBLE PRECISION pi,clite,herg,hkev,pmgm,emgm
      DOUBLE PRECISION kboltz,msun,mjy,emerg,charg,pc,re0
      DOUBLE PRECISION sigtom,gconst,sbconst,aconst,gad4_3
      parameter(pi=3.14159D0,clite=3.D10,herg=6.626D-27)
      parameter(hkev=4.15D-18,pmgm=1.67D-24,emgm=9.11D-28)
      parameter(kboltz=1.38D-16,msun=1.99D33,mjy=1.D-26)
      parameter(emerg=emgm*clite**2,charg=4.8D-10,pc=3.09D18)
      parameter(re0=2.81794D-13,sigtom=6.65D-25,gconst=6.67D-8)
      parameter(sbconst=5.67D-5,aconst=7.56D-15,gad4_3=4.D0/3.D0)

